# Netlify rules

# Handle 301 redirects for old pages: https://www.netlify.com/docs/redirects/
[[redirects]]
  from = "/elevateDMS/"
  to = "/elevate-dms"
  status = 301
[[redirects]]
  from = "/elevateIDX/"
  to = "/elevate-idx"
  status = 301
[[redirects]]
  from = "/elevateSP/"
  to = "/elevate-social-pro"
  status = 301
[[redirects]]
  from = "/getStarted/"
  to = "/get-started"
  status = 301
[[redirects]]
  from = "/support/"
  to = "https://elmstreettechnology.zendesk.com/hc/en-us"
  status = 301
[[redirects]]
  from = "/Support/"
  to = "https://elmstreettechnology.zendesk.com/hc/en-us"
  status = 301

[[redirects]]
  from = "/about-us/testimonials.asp"
  to = "/testimonials"
  status = 301
[[redirects]]
  from = "/about-us/coverage.asp"
  to = "/markets"
  status = 301

[[redirects]]
  from = "/privacy.asp"
  to = "/privacy"
  status = 301
[[redirects]]
  from = "/terms-of-service.asp"
  to = "/terms-of-service"
  status = 301
[[redirects]]
  from = "/DMCA.asp"
  to = "/dmca"
  status = 301

[[redirects]]
  from = "/blog.asp"
  to = "/blog"
  status = 301

# Redirect query params: https://www.netlify.com/docs/redirects/#query-params
[[redirects]]
  from = "/blog.asp"
  to = "/blog/tag/:tag"
  status = 301
  query = {tag = ":tag"}
[[redirects]]
  from = "/blog.asp"
  to = "/blog/tag/:cat"
  status = 301
  query = {cat = ":cat"}

[[redirects]]
  from = "/migration"
  to = "/upgrade"
  status = 301

[[redirects]]
  from = "/LiveEvents"
  to = "/liveevents"
  status = 301

[[redirects]]
  from = "/BootCamps"
  to = "/bootcamps"
  status = 301

[[redirects]]
  from = "/nextsteps"
  to = "/boot_camp_extras"
  status = 301

[[redirects]]
  from = "/leadcalc"
  to = "/leadgencalculator"
  status = 301